spring:
  output:
    ansi:
      enabled: ALWAYS

  datasource:
    url: 
    driver-class-name: org.postgresql.Driver
    username: 
    password: 
    hikari:
      connection-test-query: SELECT 1
      data-source-properties: stringtype=unspecified

  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.CockroachDB201Dialect
    show-sql: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
server:
  port: 9090
