spring:
  output:
    ansi:
      enabled: ALWAYS

  datasource:
    url: 
    driver-class-name: org.postgresql.Driver
    username: 
    password: 
    hikari:
      connection-test-query: SELECT 1
      data-source-properties: stringtype=unspecified

  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.CockroachDB201Dialect
    show-sql: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
server:
  port: 9090

app:
  database:
    name: team_blue_privacy_monitoring
    table: specification_changes

  github:
    access-token:

  check-interval-ms: 5000

  last-checked-time: 2022-01-31 16:00:00
